### ISSUE TITLE
ARM64  sudo python redroid.py -a 11.0.0 -gmnw   Error

### ISSUE THREAD

**Issue by GeekWorkCode** [ayasa520/redroid-script#7]
Downloading OpenGapps now .....
Extracting archive...
/home/ubuntu/.cache/redroid/downloads/open_gapps.zip
/tmp/ogapps/extract
    Processing app package : /tmp/ogapps/extract/Core/datatransfertool-all.tar.lz
tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Traceback (most recent call last):
  File "/home/ubuntu/redroid-script/redroid.py", line 86, in <module>
    main()
  File "/home/ubuntu/redroid-script/redroid.py", line 47, in main
    Gapps().install()
  File "/home/ubuntu/redroid-script/stuffs/general.py", line 34, in install
    self.copy()
  File "/home/ubuntu/redroid-script/stuffs/gapps.py", line 48, in copy
    run(["tar", "--lzip", "-xvf", os.path.join(self.extract_to, "Core", lz_file), "-C", os.path.join(self.extract_to, "appunpack")])
  File "/home/ubuntu/redroid-script/tools/helper.py", line 22, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['tar', '--lzip', '-xvf', '/tmp/ogapps/extract/Core/datatransfertool-all.tar.lz', '-C', '/tmp/ogapps/extract/appunpack']' returned non-zero exit status 2

**Comment by ayasa520** [comment]
Install lzip with your package manager.

**Comment by GeekWorkCode** [comment]
> Install lzip with your package manager.

Thank you for your help
