### ISSUE TITLE
An error occurs when the Oracle ARM64 server starts

### ISSUE THREAD

**Issue by GeekWorkCode** [ayasa520/redroid-script#9]
1、python redroid.py -a 11.0.0 -gmnw
2、docker run -itd --rm --privileged -v ~/var/data11:/data -p 5555:5555 redroid/redroid:11.0.0-gapps-ndk-magisk-widevine androidboot.use_memfd=1 ro.product.cpu.abilist=x86_64,arm64-v8a ro.product.cpu.abilist64=x86_64,arm64-v8a ro.dalvik.vm.isa.arm64=x86_64 ro.enable.native.bridge.exec=1 ro.dalvik.vm.native.bridge=libndk_translation.so ro.ndk_translation.version=0.2.2 redroid.gpu.mode=guest

Connect black screen, only the notification bar display.
--------- beginning of crash
04-02 11:28:18.205 51171 51171 E AndroidRuntime: FATAL EXCEPTION: main
04-02 11:28:18.205 51171 51171 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 51171
04-02 11:28:18.205 51171 51171 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at bml.a(PG:25)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at boa.a(PG:6)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at mc.b(PG:75)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at atg.a(PG:32)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at ara.a(PG:31)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at com.google.android.setupwizard.SetupWizardApplication.onCreate(PG:13)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	... 8 more
04-02 11:28:18.205 51171 51171 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at bml.a(PG:27)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	... 15 more
04-02 11:28:18.205 51171 51171 E AndroidRuntime: Caused by: java.lang.SecurityException: WifiService: Permission denied
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.net.wifi.IWifiManager$Stub$Proxy.getCurrentNetwork(IWifiManager.java:3133)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	at android.net.wifi.WifiManager.getCurrentNetwork(WifiManager.java:4993)
04-02 11:28:18.205 51171 51171 E AndroidRuntime: 	... 17 more

**Comment by GeekWorkCode** [comment]
logcat Checks the error log

04-02 11:08:23.160     0     0 E init    : mkdir("/dev/pts", 0755) failed File exists
04-02 11:08:23.164     0     0 E init    : mount("sysfs", "/sys", "sysfs", 0, NULL) failed Device or resource busy
04-02 11:08:23.166     0     0 E init    : mount("selinuxfs", "/sys/fs/selinux", "selinuxfs", 0, NULL) failed No such file or directory
04-02 11:08:23.169     0     0 E init    : mknod("/dev/kmsg", S_IFCHR | 0600, makedev(1, 11)) failed File exists
04-02 11:08:23.171     0     0 E init    : mknod("/dev/random", S_IFCHR | 0666, makedev(1, 8)) failed File exists
04-02 11:08:23.174     0     0 E init    : mknod("/dev/urandom", S_IFCHR | 0666, makedev(1, 9)) failed File exists
04-02 11:08:23.177     0     0 E init    : mknod("/dev/ptmx", S_IFCHR | 0666, makedev(5, 2)) failed File exists
04-02 11:08:23.178     0     0 E init    : mknod("/dev/null", S_IFCHR | 0666, makedev(1, 3)) failed File exists

**Comment by pxd0207** [comment]
1、
```
apt install linux-modules-extra-`uname -r`
modprobe binder_linux devices="binder,hwbinder,vndbinder"
modprobe ashmem_linux
```
2、
`python redroid.py -a 11.0.0 -mnw`  //gapps 好像有问题, 造成黑屏
3、`docker run -itd --privileged -v ~/data:/data -p 5555:5555 redroid/redroid:11.0.0-magisk-widevine  androidboot.redroid_gpu_mode=guest ` //换成redroid-script 构建的 image 名
![image](https://user-images.githubusercontent.com/55773646/229662934-89f5ee75-5905-4da0-9386-5751d8459062.png)

**Comment by ayasa520** [comment]
Is the normal redroid image working?

**Comment by GeekWorkCode** [comment]
> Is the normal redroid image working?

Normal redroid image works fine。Last week, I successfully integrated gapp once, but after deleting it later, I couldn’t succeed

**Comment by ayasa520** [comment]
I don't have ARM devices now, I will work on it later

**Comment by xAffan** [comment]
Use magisk module to integrate gapps.

**Comment by xAffan** [comment]
i am stuck on uncertified warning, though. I tried using safetynet fix but that caused adb devices to go unauthorized so can't test that. I have already put id through google's website, it still doesn't work.
